// Fixture data — used when LOB_API_KEY is unset.
// Deterministic: the same letter always gets the same mail id, the same page
// count and the same expected delivery date offset.

import { createHash } from "node:crypto";
import { LETTER, POSTCARD_6X4, renderPdf, wrap, type PdfPage } from "./pdf.js";

export interface MailAddress {
  name: string;
  company?: string;
  addressLine1: string;
  addressLine2?: string;
  addressCity: string;
  addressState: string;
  addressZip: string;
  addressCountry?: string;
}

/**
 * USPS First-Class transit estimates Lob quotes for its own products, in
 * business days. We use the same numbers so the fixture's expected delivery
 * date lands where a real one would.
 */
const TRANSIT_DAYS: Record<string, number> = {
  usps_first_class: 5,
  usps_standard: 8,
};

/** Add N business days to a date, skipping weekends the way carriers do. */
export function addBusinessDays(start: Date, days: number): Date {
  const d = new Date(start.getTime());
  let remaining = days;
  while (remaining > 0) {
    d.setUTCDate(d.getUTCDate() + 1);
    const day = d.getUTCDay();
    if (day !== 0 && day !== 6) remaining -= 1;
  }
  return d;
}

export function expectedDeliveryDate(mailType: string, from: Date = new Date()): string {
  const days = TRANSIT_DAYS[mailType] ?? TRANSIT_DAYS.usps_first_class;
  // Lob prints and hands off the next business day; transit starts from there.
  return addBusinessDays(from, days + 1).toISOString().slice(0, 10);
}

/** Stable id in Lob's own `ltr_…` / `psc_…` shape, derived from the payload. */
export function fixtureMailId(prefix: string, payload: unknown): string {
  const digest = createHash("sha256").update(JSON.stringify(payload)).digest("hex").slice(0, 16);
  return `${prefix}_fixture_${digest}`;
}

function addressLines(a: MailAddress): string[] {
  return [
    a.name,
    a.company ?? "",
    a.addressLine1,
    a.addressLine2 ?? "",
    `${a.addressCity}, ${a.addressState} ${a.addressZip}`,
    (a.addressCountry ?? "US").toUpperCase() === "US" ? "" : (a.addressCountry ?? "").toUpperCase(),
  ].filter(Boolean);
}

/**
 * Render a letter proof: a #10 window-envelope address block on page 1 followed
 * by the body text, wrapped and paginated the way Lob's own renderer does.
 */
export function renderLetterPreview(args: {
  to: MailAddress;
  from: MailAddress;
  body: string;
  color: boolean;
  doubleSided: boolean;
  mailId: string;
}): { pdfBase64: string; pageCount: number } {
  const margin = 72; // 1 inch
  const bodySize = 11;
  const lineHeight = 15;
  const contentWidth = LETTER.width - margin * 2;

  const lines = wrap(args.body, bodySize, contentWidth);

  const pages: PdfPage[] = [];
  let cursor = 0;

  while (cursor < lines.length || pages.length === 0) {
    const first = pages.length === 0;
    const page: PdfPage = { width: LETTER.width, height: LETTER.height, text: [], rects: [] };

    let y = LETTER.height - margin;

    if (first) {
      // Return address, top-left, small.
      for (const line of addressLines(args.from)) {
        page.text.push({ x: margin, y, size: 8.5, value: line });
        y -= 11;
      }

      // Recipient block positioned for a #10 double-window envelope.
      y = LETTER.height - 216;
      page.rects!.push([margin - 8, y - 62, 288, 84]);
      let ay = y;
      for (const line of addressLines(args.to)) {
        page.text.push({ x: margin, y: ay, size: 11, bold: ay === y, value: line });
        ay -= 14;
      }

      y = LETTER.height - 340;
    }

    // Body text fills whatever is left of the page.
    const bottom = margin + 48;
    while (cursor < lines.length && y > bottom) {
      // A blank line still advances the cursor; emitting an empty text run
      // would only bloat the stream.
      if (lines[cursor]) page.text.push({ x: margin, y, size: bodySize, value: lines[cursor] });
      y -= lineHeight;
      cursor += 1;
    }

    pages.push(page);
    if (cursor >= lines.length) break;
  }

  // Footer on every page: the proof is clearly a proof.
  pages.forEach((page, i) => {
    page.text.push({
      x: margin,
      y: 46,
      size: 7.5,
      value: `${args.mailId}  |  page ${i + 1} of ${pages.length}  |  ${args.color ? "color" : "black & white"}, ${args.doubleSided ? "double-sided" : "single-sided"}`,
    });
    page.text.push({
      x: margin,
      y: 34,
      size: 7.5,
      value: "PREVIEW - generated by x402-print-mail in fixture mode. Not submitted to a print partner.",
    });
  });

  return { pdfBase64: renderPdf(pages), pageCount: pages.length };
}

/** Render a postcard proof: front (message) and back (address block), 6" x 4". */
export function renderPostcardPreview(args: {
  to: MailAddress;
  from: MailAddress;
  front: string;
  back: string;
  mailId: string;
}): { pdfBase64: string; pageCount: number } {
  const { width, height } = POSTCARD_6X4;
  const margin = 24;

  const frontPage: PdfPage = { width, height, text: [], rects: [] };
  let y = height - margin - 12;
  for (const line of wrap(args.front, 13, width - margin * 2)) {
    frontPage.text.push({ x: margin, y, size: 13, value: line });
    y -= 17;
  }

  const backPage: PdfPage = { width, height, text: [], rects: [] };
  // Left half: the message. Right half: the address block and stamp box.
  let by = height - margin - 10;
  for (const line of wrap(args.back, 9, width / 2 - margin - 8)) {
    backPage.text.push({ x: margin, y: by, size: 9, value: line });
    by -= 12;
  }
  backPage.rects!.push([width - margin - 52, height - margin - 40, 52, 40]);
  backPage.text.push({ x: width - margin - 46, y: height - margin - 24, size: 7, value: "POSTAGE" });

  let ay = height / 2 - 6;
  for (const line of addressLines(args.to)) {
    backPage.text.push({ x: width / 2 + 6, y: ay, size: 10, bold: ay === height / 2 - 6, value: line });
    ay -= 13;
  }
  backPage.text.push({ x: margin, y: 20, size: 6.5, value: `${args.mailId} | PREVIEW - fixture mode` });

  return { pdfBase64: renderPdf([frontPage, backPage]), pageCount: 2 };
}
